name: Go CI

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'src/go.mod'

    - name: Install dependencies
      run: go mod tidy
      working-directory: src

    - name: Build
      run: |
        go list ./...
      working-directory: src

    - name: Run tests
      run: go test ./...
      working-directory: src


